name: Testing

on:
  - push

jobs:
  testing:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version:
          - "3.6"
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"

    services:
      redis:
        image: redis
        ports:
          - 6379/tcp
      memcached:
        image: memcached
        ports:
          - 11211/tcp
      mongodb:
        image: bitnami/mongodb
        ports:
          - 27017/tcp

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache multiple Pips
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
          key: ${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('**/setup.py') }}
      - run: pip install .
      - name: Install dev dependencies
        run: |
          pip install \
            redis \
            pymongo \
            python-memcached \
            "flask<1.1" \
            "jinja2<2.12" \
            "markupsafe<1.2" \
            "itsdangerous<0.25" \
            "Werkzeug<1.1" \
            "pymongo<4.1" \
            flask_sqlalchemy
      - run: make test
